config/routes.rb
Rails.application.routes.draw do
	authenticate :user do
	  resources :reviews, only: [:new, :create, :edit, :update, :destroy]
	end
	resources :reviews, only: [:index, :show]
	
	devise_for :users
	resources :courses

	root 'index#index'
	authenticate :user do
		get 'dashboard', to: 'dashboard#index', :as => "dashboard"
		get 'load', to: 'scraper#index' 
	end
	
	get 'load', to: 'scraper#index' 
	
	get 'courses', to: 'courses#index'

	get 'platforms', to: 'platforms#index', :as => "platforms"
	get 'platforms/:id', to: 'platforms#show', :as => "platform"

	get 'instructors', to: 'instructors#index', :as => "instructors"
	get 'instructors/:id', to: 'instructors#show', :as => "instructor"
	
	get 'categories', to: 'categories#index', :as => "categories"
	get 'categories/:id', to: 'categories#show', :as => "category"
	
	get 'about', to: 'static#about', :as => "about"	
	get 'contact', to: 'static#contact', :as => "contact"
	get 'moocs', to: 'static#moocs', :as => "moocs"
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create	
    course = Course.find(params[:course_id])
    @review = course.reviews.build
	
	@review.user_id = current_user.id
	@review.rating = review_params.fetch(:rating)
	@review.review = review_params.fetch(:review)
	
    respond_to do |format|
      if @review.save
		rate = 0
		course.reviews.each do |r|
			rate += r.rating
		end
		course.rating = (rate / course.reviews.count.to_f)
		course.save
		puts "ALL RATING: " + (course.rating).to_s
        format.html { redirect_to course, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to '/dashboard', notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :review)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for(review) do |f| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rating %>
    <%= f.number_field :rating %>
  </div>

  <div class="field">
    <%= f.label :review %>
    <%= f.text_field :review %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/_new.html.erb
<h1>New Review</h1>

<%= form_for(@review) do |f| %>
	<%= f.hidden_field :course_id, :name => "course_id", :value => @course.id %>

  <div class="field">
    <%= f.label :rating %>
    <%= f.number_field :rating, placeholder: 3, min: 1, max: 5  %>
  </div>

  <div class="field">
    <%= f.label :review %>
    <%= f.text_area :review, placeholder: 'Enter your review here' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', courses_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Review</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.review %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rating %>
    <%= f.number_field :rating %>
  </div>

  <div class="field">
    <%= f.label :review %>
    <%= f.text_field :review %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Review:</strong>
  <%= @review.review %>
</p>

<p>
  <strong>User:</strong>
  <%= User.find(@review.user_id).email %>
</p>

<p>
  <strong>Course:</strong>
  <%= Course.find(@review.course_id).name %>
</p>
<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>