config/routes.rb
Rails.application.routes.draw do
	authenticate :user do
	  resources :reviews, only: [:new, :create, :edit, :update, :destroy]
	end
	resources :reviews, only: [:index, :show]
	
	devise_for :users
	resources :courses

	root 'index#index'
	authenticate :user do
		get 'dashboard', to: 'dashboard#index', :as => "dashboard"
		get 'load', to: 'scraper#index' 
	end
	
	get 'load', to: 'scraper#index' 
	
	get 'courses', to: 'courses#index'

	get 'platforms', to: 'platforms#index', :as => "platforms"
	get 'platforms/:id', to: 'platforms#show', :as => "platform"

	get 'instructors', to: 'instructors#index', :as => "instructors"
	get 'instructors/:id', to: 'instructors#show', :as => "instructor"
	
	get 'categories', to: 'categories#index', :as => "categories"
	get 'categories/:id', to: 'categories#show', :as => "category"
	
	get 'about', to: 'static#about', :as => "about"	
	get 'contact', to: 'static#contact', :as => "contact"
	get 'moocs', to: 'static#moocs', :as => "moocs"
end

app/views/layouts/_footer.erb
<footer class="effect7">
	<div class="container">
		<div class="row">
			<ul class="list-inline footerlinks">
			  <li>
				<%= link_to('About', about_path, :method => :get) %>
			  </li>
			  <li>
				<%= link_to('Contact', contact_path, :method => :get) %>
			  </li>
			  <li>
				<%= link_to('MOOCs', moocs_path, :method => :get) %>
			  </li>
			</ul>
		</div>
	</div>
</footer>

app/views/layouts/_header.erb
<header class="effect6">
	<div class="container">
		<nav class="navbar navbar-default">
		  <div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
			  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			  </button>
			  <a class="navbar-brand headline" href="\">MOOCFinder</a>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			  <ul class="nav navbar-nav">
				<li class="dropdown">
				  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Browse<span class="caret"></span></a>
				  <ul class="dropdown-menu">
					<li><%= link_to('Courses', courses_path)  %></li>
					<li><%= link_to('Categories', categories_path)  %></li>
					<li><%= link_to('Platforms', platforms_path)  %></li>
					<li><%= link_to('Instructors', instructors_path)  %></li>
				  </ul>
				</li>
			  </ul>
			  <%= form_tag(courses_path, method: 'get', :class => 'navbar-form navbar-left') do %>
				<div class="input-group input-group-lg">
					<%= label_tag :keywords, nil, class: "sr-only" %>
					<%= text_field_tag :keywords, nil,
						placeholder: "search course",	
						class: "form-control input-lg"%>
					<span class="input-group-btn">
						<button type="submit" class="btn btn-default btn-sm">
						<span class="glyphicon glyphicon-search" aria-hidden="true"> </span>
						</button>
					</span>
				</div>
			<% end %>	
			<% if user_signed_in? %>
			  <ul class="nav navbar-nav navbar-right">
				<li><a href="/dashboard">Dashboard</a></li>
				<li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
			  </ul>
			<% else %>
			  <ul class="nav navbar-nav navbar-right">
				<li><%= link_to('Login', new_user_session_path)  %></li>
				<li><%= link_to('Register', new_user_registration_path)  %></li>
			  </ul>
			<% end %>
			</div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>
	</div>				
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moocfinder</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag    'style', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
	<%= render "layouts/header" %>
	<div class="wrapper container">
		<% if notice.present? %>
			<aside class="alert alert-info">
				<%= notice %>
			</aside>
		<% end %>
		<% if alert.present? %>
			<aside class="alert alert-danger">
				<%= alert %>
			</aside>
		<% end %>
		<div class="panel effect2">
			<%= yield %>
		</div>		
		<div class="push"></div>
	</div>
	<%= render "layouts/footer" %>
  </body>
</html>